[package]
name = "asf-fyb-forms"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
serde = "1.0.198"
shuttle-axum = "0.43.0"
shuttle-runtime = "0.43.0"
sqlx = "0.7.4"
tokio = "1.28.2"
